### PR TITLE
Factorial using for loop

### PR DESCRIPTION
**Pull request by Shamik1836**

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@Shamik1836 The number 20 already exists, you need to update the number 51.

**Comment by Shamik1836** [comment]
Okay I will be doing that shortly

**Comment by Shamik1836** [comment]
Done editing. Please have a look

**Comment by Shamik1836** [comment]
Have you seen my pr yet?

**Comment by Subham-Maity** [comment]
@Shamik1836 
1. First markdown links with anchor ```51``` is not working (click and check your heading if is it working or not?)
2. Add your program after 50 number question (problem: At the end of the markdown sheet, you added your problems)
3. As you mentioned in the explanation section, you are using for loops instead of recursion It's not a proper approach (A code's approach describes the logic behind it)
4. For loop questions should be added to the for loop section not the array section 

Screenshot 2022-10-06 150130
r loop, links with anchor should be in the for-loop section

**Comment by Shamik1836** [comment]
So as I understand, I need to move the factorial program from array section to the for loop section and give it a number 51, and also I need to write a proper approach am I correct?

**Comment by Subham-Maity** [comment]
@Shamik1836 and the anchor 51 failed, so you must fix it so that it jumps directly to the heading 51 no question that you will be adding 


https://user-images.githubusercontent.com/97989643/194307755-2274cd6b-e83d-4e96-8e18-ba626eb9cf0d.mp4

**Comment by Shamik1836** [comment]
I have made the changes as asked by you @Subham-Maity, kindly check and let me know if it's alright or not

**Comment by Subham-Maity** [comment]
@Shamik1836 
**1.Correct the spelling initialized** 
**2.Approach write inside the code block like this** 
```js
Here at first two variables are being initialized one is fact which is initialized to 1 .................................
.....................
```
**3.Place the problem after 50. Pascal's Triangle problem** 


https://user-images.githubusercontent.com/97989643/194374289-e433512d-b734-4416-a7c2-88f63e001f16.mp4

4. Remains are perfect

**Comment by Shamik1836** [comment]
Hey, I have the made the changes as asked by you , have a look now and let me know if it's alright or not?

**Comment by Subham-Maity** [comment]
@Shamik1836 Nice Work!

**Pull request merged**
